name: Publish Module

on:
  push:
    tags:
      - "*"

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
